//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RexSimulatorGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RexSimulatorGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream duck_quack {
            get {
                return ResourceManager.GetStream("duck_quack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S32D00080000310EFFFF111DFFFF020100009120000012210001C301FFFF23380002A03FFFFBCE01FF801EE300042E
        ///S32D0008000A600803EE600802EB600802D8600803F560080161600805EE60080C7160080CD11EE300019FE00000A0
        ///S32D0008001481E00001701000008FE000001EE1000150F0000081070003111B0001A01FFFFD81070001111B00FFFE
        ///S32D0008001E50F0000081070003111B0002A01FFFFD81E000009107000050F000001EE3000394E0000095E00001D1
        ///S32D0008002896E0000284E0000385E0000401410000144300011441000186400000B06FFFFD86500000155100014C
        ///S32D000800329640000014410001B06FFFFB8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string monitor_srec {
            get {
                return ResourceManager.GetString("monitor_srec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RexBoardPhoto {
            get {
                object obj = ResourceManager.GetObject("RexBoardPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
